### PR TITLE
Propagate transitive_deps

### LINKED ISSUE #8: AOTing requires transitive deps
```
(ns test
  (:require [cognitect.aws.client.api :as aws])
  (:gen-class))

(defn -main []
  (println (keys (aws/ops (aws/client {:api :sns})))))
```

currently fails with:

> Execution error (FileNotFoundException) at cognitect.aws.client.api/loading (api.clj:4).
> Could not locate clojure/core/async__init.class, clojure/core/async.clj or clojure/core/async.cljc on classpath.

The transitive deps of the cognitect.aws.client.api library need to be propagated, PR to follow.

### PR DESCRIPTION
**Pull request by markdingram**
Fixes #8

### CODE REVIEW

**Comment by simuons** [comment]
Thanks! I'll take a deeper look on weekend.
Could you add a test for this. I know there is no CI currently, I'll try to setup it ASAP.

**Comment by markdingram** [comment]
Hi! 

Yes I'll add a test. If you want to setup CI on Github Actions check https://github.com/markdingram/bazel-cdk-clojure/actions/runs/162061319/workflow (or I could do that in a PR too?)

**Comment by markdingram** [comment]
Hopefully good to go now! @simuons

**Comment by simuons** [comment]
Hi. I've merged your other PR https://github.com/simuons/rules_clojure/pull/11 and not this one has conflicts. Could you resolve them and I'll merge.

**Review by simuons — APPROVED** [review]

**Pull request merged**
